name: Building recovery

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni -b twrp-12.1-deprecated
  DEVICE: LF7
  DT_LINK: https://github.com/T0UB3S/android_device_tecno_TECNO-LF7
  DT_PATH: device/tecno/LF7
  TARGET: bootimage
  TZ: America/caracas

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -f
          # Install specific dependencies from a file (apt.txt)
          cat apt.txt | xargs sudo apt-get install -y

      - name: Sync recovery source and device tree
        run: |
          mkdir work
          cd work
          repo init -u $MANIFEST --depth=1
          repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
          repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
          git clone --depth=1 $DT_LINK $DT_PATH

      - name: Build
        run: |
          cd work
          . build/envsetup.sh && lunch omni_$DEVICE-eng &&export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET

      - name: Release boot image
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: TWRP_12.1
          name: TWRP-LF7
          files: |
            work/out/target/product/LF7/boot.img
