name: Building recovery

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
  DEVICE: LF7
  DT_LINK: https://github.com/T0UB3S/android_device_tecno_TECNO-LF7
  DT_PATH: device/tecno/LF7
  TARGET: bootimage
  TZ: America/caracas

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
            
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -f
          # Install specific dependencies from a file (apt.txt)
          cat apt.txt | xargs sudo apt-get install -y

      - name: Initializing environment
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          docker rmi `docker images -q`
          sudo apt-get remove aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
          git config --global user.name "T0UB3S"
          git config --global user.email "elyisverantohan@gmail.com"         
          sudo -E apt-get -y purge azure-cli zulu* hhvm firefox powershell 
          sudo -E apt-get clean
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
          sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo

      - name: Sync recovery source and device tree
        run: |
          mkdir work
          cd work
          repo init -u $MANIFEST --depth=1
          repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
          repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
          git clone --depth=1 $DT_LINK $DT_PATH

      - name: Build
        run: |
          cd work
          . build/envsetup.sh && lunch omni_$DEVICE-eng &&export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET

      - name: Release boot image
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: TWRP_12.1
          name: TWRP-LF7
          files: |
            work/out/target/product/LF7/boot.img
